### ISSUE TITLE
[DESC] broken link

### ISSUE THREAD

**Issue by vinnyA3** [Nerdherdx/Nerdherdx.github.io#1]
link ([nerdherdx.github.io](nerdherdx.github.io)) is broken 😿

**Comment by VoidNakamura-zz** [comment]
> 
> 
> link ([nerdherdx.github.io](nerdherdx.github.io)) is broken 😿

Should be back up! Cheers!


https://voidnakamura.github.io/MoviesNetwork.github.io/

**Comment by vinnyA3** [comment]
Cool, Plus Ultra!! 💪🏽
